project:
  type: website
  output-dir: docs
website:
  title: "Suraj Jaiswal"
  site-url: https://jaiswalsuraj487.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: about.qmd
      #   text: About
      - href: blogs/index.qmd
        text: Blogs
      - href: publications_and_projects/index.qmd 
        text: Publications and Projects
    right: 
      - href: resume/Suraj_Jaiswal_Resume.pdf
        text: Resume
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



