project:
  type: website
  output-dir: docs
website:
  title: "Suraj Jaiswal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blogs/index.qmd
        text: Blogs
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



